import { NextPage } from "next";
import Head from "next/head";
import { Page, pagesApi } from "@entities/page";

interface PageViewProps {
  page: Page;
}

const PageView: NextPage<PageViewProps, PageViewProps> = (params) => {
  params.page.id;
  return (
    <div>
      <Head>
        <title>{params.page.id}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      Page {params.page.id}
    </div>
  );
};

PageView.getInitialProps = async (context) => {
  const { slug } = context.query;
  const page = await pagesApi.get(slug as any);
  return { page: page.data };
};

export default PageView;
